# Generated by Django 4.2.3 on 2023-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
