# Generated by Django 4.2.3 on 2023-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona_apellido_persona_correo_persona_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='documento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
