# Generated by Django 4.2.3 on 2023-07-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
