# Generated by Django 4.2.3 on 2023-07-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persona_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='documento',
            new_name='numero_documento',
        ),
    ]
